### PR TITLE
splunk-devops-exted SECURITY-496, splunk-devops SECURITY-479 fixed by…

### PR DESCRIPTION
**Pull request by fengxx**
splunk-devops-exted SECURITY-496, splunk-devops SECURITY-479 fixed by 1.5.0 release

### CODE REVIEW

**Comment by daniel-beck** [comment]
@fengxx I'll take a look at the plugins today, and merge if it looks good.

**Comment by fengxx** [comment]
@daniel-beck do you have a chance to review the fix?

**Comment by daniel-beck** [comment]
@fengxx Sorry, not yet. Still very close to the top of my "to do" list!

**Comment by daniel-beck** [comment]
@fengxx This was planned for today, but then https://jenkins.io/security/advisory/2017-04-27/ happened and ate what time I had put aside. I will be traveling the next few days, new estimate: Tuesday.

**Comment by fengxx** [comment]
close this out since it has two fixes, which may take longer. I will split them into two PR

**Pull request closed without merging**
