### PR TITLE
blacklist qtest plugin v1.2.0 because it's draft release

### PR DESCRIPTION
**Pull request by qasdev**
blacklist qtest plugin v1.2.0 because it's draft release and not the latest release

### CODE REVIEW

**Comment by daniel-beck** [comment]
If you want to publish experimental pre-release versions, indicate that in the version number with 'alpha' or 'beta'. See https://jenkins.io/content/experimental-plugins-update-center/

**Comment by qasdev** [comment]
Hi @daniel-beck ,
How long can this merge request affects the blacklist of qtest plugin v1.2.0.
Thank you very very much.

**Comment by qasdev** [comment]
Yeah, I have seen it affects my plugin release, thank you :)

**Comment by daniel-beck** [comment]
This will apply indefinitely until a change removing the entry is merged.

**Pull request merged**
