### PR TITLE
[JENKINS-45126] Remove Gradle plugin 1.27

### PR DESCRIPTION
**Pull request by daniel-beck**
https://issues.jenkins-ci.org/browse/JENKINS-45126

Something went wrong with the 1.27 release.

CC @wolfs

### CODE REVIEW

**Comment by wolfs** [comment]
Thanks for the heads up. I'll release 1.27.1 today.

**Comment by oleg-nenashev** [comment]
@daniel-beck FYI

**Comment by wolfs** [comment]
@daniel-beck I just released version 1.27.1, which should fix the issue. Please go ahead and blacklist 1.27.

**Comment by daniel-beck** [comment]
@wolfs Thanks for the update. I checked and it looks better.

Probably not really necessary since nobody is offered 1.27 anymore, but to prevent it from showing in the archive, and for whenever we add old version support…

**Pull request merged**
