### PR TITLE
update claim plugin vulnerable version

### PR DESCRIPTION
**Pull request by Greybird**
I cannot close SECURITY-296 as I cannot see it myself. (I used JENKINS-43811 for that)
I edited https://wiki.jenkins.io/display/JENKINS/Script+Security+Support+in+Plugins with the information needed.
Please tell me if I need to do other things.

### CODE REVIEW

**Comment by daniel-beck** [comment]
SECURITY-296 has been closed long ago as the need to track it privately is gone.

**Comment by Greybird** [comment]
Ok, noted. I updated the wiki page.
Should I do something else or is this PR enough to close the vulnerability?

**Comment by Greybird** [comment]
Gentle reminder 😄 , do I miss something?

**Comment by daniel-beck** [comment]
No -- this repo is just quickly becoming my personal hall of shame 😞

**Comment by Greybird** [comment]
Hello @daniel-beck ,

Sorry to burden you with this PR...
It seems to me the issue reported here is an infrastructure one not related to the content of the PR ?

I'm also wondering if this PR not being merged is responsible of the fact that the plugin wiki page still shows 2.9 as the latest released version?
I have some mixed info from https://plugins.jenkins.io/claim which shows a 2.10 version on the top, with a 2.9 in the latest release field. Of course, the wiki page https://wiki.jenkins.io/display/JENKINS/Claim+plugin is also on 2.9...

If you confirm this is not, I will send a mail to the dev mailing list.

Thanks,

Arnaud

**Comment by daniel-beck** [comment]
@Greybird 

> Sorry to burden you with this PR...

No worries, I just want to make sure before applying this change that it's correct to do so.

>  It seems to me the issue reported here is an infrastructure one not related to the content of the PR ?

I agree. Just ignore the previous comment and PR build.

> which shows a 2.10 version on the top, with a 2.9 in the latest release field. Of course, the wiki page https://wiki.jenkins.io/display/JENKINS/Claim+plugin is also on 2.9...

The wiki is heavily cached; and the plugins site scrapes it to show documentation. 2.10 is correct. See also https://wiki.jenkins.io/display/JENKINS/Claim+plugin?nocache

**Comment by daniel-beck** [comment]
@Greybird I'm sorry to have kept you waiting. I reviewed the code changes and they look reasonable. The test you added was also helpful, thanks for that.

**Pull request merged**
