### PR TITLE
Restore integrity-plugin distribution

### PR DESCRIPTION
**Pull request by anuragsen**
Change-Id: Iacf4142b8fd8156d5710c8838280ae85fc1813e6

### CODE REVIEW

**Comment by anuragsen** [comment]
Dear @daniel-beck, could you please approve this PR so that integrity-plugin distribution is restored. 
Kindly let me know if there is any outstanding task on this PR.
Thanks!

**Comment by oleg-nenashev** [comment]
@anuragsen Could you please clarify the status of https://github.com/jenkinsci/integrity-plugin/pull/24 ? It seems that the PR has been merged without addressing the feedback from @jglick

**Comment by daniel-beck** [comment]
@oleg-nenashev Actually it has AFAIUI, in https://github.com/jenkinsci/integrity-plugin/pull/24#discussion_r115224277

**Comment by oleg-nenashev** [comment]
@daniel-beck ack, right. I would prefer to get @jglick's confirmation just to be 100% sure. My comments are not the blocker for this PR since the issues are not security matter ones

**Comment by daniel-beck** [comment]
@jglick confirmed that it it looks like his PR review was appropriately addressed, and that it wasn't a security concern anyway.

**Comment by anuragsen** [comment]
@oleg-nenashev , @daniel-beck ,@jglick. Thanks for your inputs & guidance. I will incorporate the feedback from Oleg in the next iteration.

**Pull request merged**
